name: "Publish documentation 📑"
description: "Generate and publish documentation"

inputs:
  spark-3_0:
    description: 'Spark version 3.0.X'
    required: true
    default: "3.0"
  spark-3_1:
    description: 'Spark version 3.1.X'
    required: true
    default: "3.1"
  spark-3_2:
    description: 'Spark version 3.2.X'
    required: true
    default: "3.2"

runs:
  using: "composite"
  steps:
    # BUILD SCALA DOCS
    - name: Build the scaladocs 💻 [${{ inputs.spark-3_0 }}]
      run: |
        sbt -DsparkVersion=${{ inputs.spark-3_0 }} core/doc
        mkdir -p tmp/api_spark_${{ inputs.spark-3_0 }}
        cp -ar core/target/scala-2.12/api/* tmp/api_spark_${{ inputs.spark-3_0 }}/
      shell: bash

    - name: Build the scaladocs 💻 [${{ inputs.spark-3_1 }}]
      run: |
        sbt -DsparkVersion=${{ inputs.spark-3_1 }} core/doc
        mkdir -p tmp/api_spark_${{ inputs.spark-3_1 }}
        cp -ar core/target/scala-2.12/api/* tmp/api_spark_${{ inputs.spark-3_1 }}/
      shell: bash

    - name: Build the scaladocs 💻 [${{ inputs.spark-3_2 }}]
      run: |
        sbt -DsparkVersion=${{ inputs.spark-3_2 }} core/doc
        mkdir -p tmp/api_spark_${{ inputs.spark-3_2 }}
        cp -ar core/target/scala-2.12/api/* tmp/api_spark_${{ inputs.spark-3_2 }}/
      shell: bash

    # COPY API DOCS TO MDOC
    - name: Copy site and docs to gh-pages branch 💾 [{{ inputs.spark-3_0 }}]
      run: |
        mkdir -p docs/target/mdoc/docs/api/3.0
        cp -ar tmp/api_spark_${{ inputs.spark-3_0 }}/* docs/target/mdoc/docs/api/3.0/
      shell: bash

    - name: Copy site and docs to gh-pages branch 💾 [{{ inputs.spark-3_1 }}]
      run: |
        mkdir -p docs/target/mdoc/docs/api/3.1
        cp -ar tmp/api_spark_${{ inputs.spark-3_1 }}/* docs/target/mdoc/docs/api/3.1/
      shell: bash

    - name: Copy site and docs to gh-pages branch 💾 [{{ inputs.spark-3_2 }}]
      run: |
        mkdir -p docs/target/mdoc/docs/api/3.2
        cp -ar tmp/api_spark_${{ inputs.spark-3_2 }}/* docs/target/mdoc/docs/api/latest/
      shell: bash

    # BUILD MDOC
    - name: Build the microsite 💻
      run: sbt -DsparkVersion=${{ inputs.spark-3_2 }} docs/mdoc
      shell: bash

    # DEPLOY TO GITHUB PAGES
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/target/mdoc # The folder the action should deploy.
