package doric.syntax

private[doric] trait All
    extends ArrayColumns
    with TypeMatcher
    with CommonColumns
    with DStructs
    with LiteralConversions
    with MapColumns
    with NumericColumns
    with DateColumns
    with TimestampColumns
    with BooleanColumns
    with StringColumns
    with ControlStructures
    with AggregationColumns
    with CNameOps
    with BinaryColumns
    with Interpolators
    with AggregationColumns31
    with BooleanColumns31
    with NumericColumns31
    with NumericColumns32
    with StringColumns31
    with BinaryColumns32
    with ArrayColumns3x
    with CommonColumns3x
    with MapColumns3x
    with StringColumn3x
    with AggregationColumns32
