name: "Check, build & doc 🎯"
description: "Check the code, build, testing & generate project documentation"

inputs:
  testing:
    description: 'Whether to execute tests or not'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: olafurpg/setup-scala@v13
    - uses: coursier/cache-action@v6
    - name: Code Format
      if: inputs.testing == 'true'
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} scalafmtCheckAll
      shell: bash
    - name: Test & coverage 📋
      if: inputs.testing == 'true'
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} coverage core/test coverageReport coverageAggregate
      shell: bash
    - name: Publish coverage to codecov 📊
      if: inputs.testing == 'true' && env.SCOPE == 'uploadReports'
      uses: codecov/codecov-action@v2
      with:
        files: ./target/scala-2.12/scoverage-report/scoverage.xml
        fail_ci_if_error: true
        verbose: false
        flags: ${{ env.SPARK_VERSION }}
    - name: Build the microsite 💻
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} docs/mdoc
      shell: bash
    - name: Build the scaladocs 💻
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} core/doc
      shell: bash
