name: "Check, build & doc 🎯"
description: "Check the code, build, testing & generate project documentation"

runs:
  using: "composite"
  steps:
    - name: "Printing environment"
      run: |
        echo ""
        echo "#####################################################"
        echo "#                                                   #"
        echo "# Running action for $SPARK_VERSION [scope $SCOPE]"
        echo "#                                                   #"
        echo "#####################################################"
        echo ""
      shell: bash

      # SETUP
    - uses: olafurpg/setup-scala@v13
    - uses: coursier/cache-action@v6

      # CHECK CODE FORMAT
    - name: Code Format
      if: env.SCOPE == 'testing' || env.SCOPE == 'uploadReports'
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} scalafmtCheckAll
      shell: bash

      # TESTING & COVERAGE
    - name: Test & coverage 📋
      if: env.SCOPE == 'testing' || env.SCOPE == 'uploadReports'
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} coverage core/test coverageReport coverageAggregate
      shell: bash

    - name: Publish coverage to codecov 📊
      if: env.SCOPE == 'uploadReports'
      uses: codecov/codecov-action@v2
      with:
        files: ./target/scala-2.12/scoverage-report/scoverage.xml
        fail_ci_if_error: true
        verbose: false
        flags: ${{ env.SPARK_VERSION }}

      # CHECK DOCUMENTATION
    - name: Build the microsite 💻
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} docs/mdoc
      shell: bash

    - name: Build the scaladocs 💻
      run: sbt -DsparkVersion=${{ env.SPARK_VERSION }} core/doc
      shell: bash
