name: ðŸ› Bug Report form
description: Report a bug using a form. >> Use this option by default <<
title: "[Bug report]: "
labels: ["bug"]
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: |
        âš ï¸ðŸ™ðŸ“šï¸ Please, before creating any issue read our [contribution guide](https://github.com/hablapps/doric/blob/main/CONTRIBUTING.md)
        Thanks for contributing!
  - type: input
    id: version
    attributes:
      label: Doric version
      description: What version of doric are you using?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please, tell us what happened and how this affects to your use case.
      placeholder: What happened?
      value: "Boom! Big reveal! I turned myself into a pickle!"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      description: What did you expect to happen?
      placeholder: What should have happened?
      value: "I programmed you to believe that."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
#  - type: checkboxes
#    id: terms
#    attributes:
#      label: Code of Conduct
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#      options:
#        - label: I agree to follow this project's Code of Conduct
#          required: true
