name: On dispatch or push development branch

on:
  push:
    #    branches:
    #      - '*doc/*'
    branches-ignore:
      - main
      - dependabot/** # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  context_dump:
#    runs-on: ubuntu-latest
#    steps:
#      - name: <DEBUG> Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#        shell: bash
  publish_doc:
    uses: ./.github/workflows/wc_publishSite.yml
    with:
      publish: "yes"
